name: 'Release with Changelog by Branch'
icon: 'tag'
branding:
  icon: 'tag'
  color: 'blue'
description: 'Create a GitHub relase with changelog for every tag you push'
inputs:
  tag:
    description: Specific tag to generate changelog against
    required: false
  tagTemplate:
    description: Tags template used to look for the previous tag
    required: false
  pathFilter:
    description: Path filter used by git log
    required: false
  grouping:
    description: Release notes generation : group the commits by title 
    required: false
  token:
    description: Personal access token (PAT) used to create releases
    required: true
  exclude:
    description: Regex to exclude commits based on their title (don't include the initial and final `/`)
    required: false
    default: ''
  template:
    description: Markdown template to be included in release notes
    required: false
    default: |
      {commits}

      {range}
  commit-template:
    description: Markdown template for each commit entry in release notes
    required: false
    default: '- {hash} {title}'
runs:
  using: 'node12'
  main: 'distribution/index.js'
